---
title: "3. Get and Clean Data: Week 2 Notes            "
output: html_notebook
---

# Data Sources

## Reading from MySQL
Databases, tables, fields, records. MySQL is free and commonly used in interweb applications.

So a database consists of lots of tables. A table would be a data frame in R, and the database tables each describe one logical component of the data. They're linked together by keys (id's).

To really test this, it's best to start a local installation of MySQL and run against that. For these examples we'll be using a genomic database provided by UC Santa Cruz.

You need to install RMySQL. Once you do that, you can connect to the database with:
```{r}
library(RMySQL)
hg19 <- dbConnect(MySQL(), user="genome", db="hg19", host="genome-mysql.cse.ucsc.edu")
allTables <- dbListTables(hg19)
length(allTables)

## now we can see the fields in a specific table and count the rows:
dbListFields(hg19, "affyU133Plus2")
dbGetQuery(hg19, "select count(*) from affyU133Plus2")

## you can extract a table into a data frame
affyData <- dbReadTable(hg19, "affyU133Plus2")
```

There's a lot of nuance in the RMySQL package, don't have time to unpack everything here.

## Reading from HDF5
HDF5 is used for storing large amounts of data in a hierarchical format.

- **groups** contain zero or more datasets and metadata
     - have a group header with group name and list of attributes
     - have a group symbol table with a list of objects in the group
- **datasets** are multidimensional arrays of data elements with metadata
     - have a header with a name, data type, dataspace, and storage layout
     - have a data array with the data
     
The R HDF5 libraries are installed through bioconductor, but they're conveniently included in this dockerfile (hopefully).
